# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('companies', '0002_auto_20160110_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
    ]
