# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('Nepal', 'Nepal')], default='Nepal', max_length=50)),
                ('state', models.CharField(choices=[('Bagmati', 'BAGMATI')], default='Bagmati', max_length=100)),
                ('city', models.CharField(choices=[('kathamdnu', 'Kathmandu')], default='Kathmandu', max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('address3', models.CharField(max_length=255)),
            ],
        ),
    ]
