# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('overview', models.TextField(verbose_name='company overview')),
                ('description', models.TextField(verbose_name='description')),
                ('website', models.URLField()),
                ('telephone', models.CharField(max_length=10)),
                ('company_size', models.CharField(blank=True, default='', max_length=6)),
                ('why_jon_us', models.TextField(verbose_name='Why join us')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Industry'),
        ),
    ]
