# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='job title')),
                ('summary', models.CharField(max_length=255, verbose_name='job summary')),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('job_level', models.CharField(choices=[('entry', 'entry'), ('intermediate', 'intermediate'), ('expert', 'expert')], default='entry', max_length=12, verbose_name='job level')),
                ('vacencies', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=255)),
                ('salary', models.CharField(default='negotiable', max_length=255, verbose_name='Salary')),
                ('expire_at', models.DateTimeField()),
                ('other_info', models.TextField(verbose_name='other information')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cat_name', models.CharField(max_length=255, verbose_name='job category name')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Job Categories',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobCategory'),
        ),
    ]
